http:
  host: 'localhost'
  port: 3000

db:
  host: 'localhost'
  port: 3306
  database: 'db_nest'
  user: 'root'
  password: '123456'

oss:
  accessKeyId: 'LTAI5t8FCcQW3jNmTby9hWM8'
  accessKeySecret: '6BGAS1Gjpb4sHQqFWmtngCMjTkaBAn'
  bucket: 'hades0512'
  region: 'oss-cn-beijing'

