http:
  host: 'localhost'
  port: 3000

db:
  host: 'localhost'
  port: 3306
  database: 'db_nest'
  user: 'root'
  password: '123456'

oss:
  accessKeyId: ''
  accessKeySecret: ''
  bucket: ''
  region: ''

